### ISSUE TITLE
Sensor sdf files are not loading

### ISSUE THREAD

**Issue by jenniferdavid** [EEEManchester/gazebo_radiation_plugin#4]
Line 43 has extra close tag /> which needs to be removed in all the sdf files.

**Comment by DrAndyWest** [comment]
Hi Jenni,

I think I found the additional close statement in [radiation_sources.sdf](https://github.com/EEEManchester/gazebo_radiation_plugin/blob/4efad1970ef8adea2e395c78b09f46b56995db51/sdf/radiation_source.sdf#L43).  That has now has been fixed.  That being said, that particular workflow might be a bit out of date, so there may be more updates in the future.

Thank you for taking the time to check the code and submit an issue ticket.
Cheers,
Andy
